name: build and run container on push

on:
  push:
    branches:
      - main
  
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
      
        - name: Build Docker image
          run: docker build -t python-app .
      
        - name: Run Docker container
          run: |
            docker run -d --name python-app python-app
            docker logs python-app
